package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Response) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "REID":
			err = z.REID.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "REID")
				return
			}
		case "RNUM":
			z.RNUM, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "RNUM")
				return
			}
		case "RESPONSE":
			z.RESPONSE, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RESPONSE")
				return
			}
		case "PAYL":
			err = z.PAYL.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "PAYL")
				return
			}
		case "WARNINGS":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "WARNINGS")
				return
			}
			if cap(z.WARNINGS) >= int(zb0002) {
				z.WARNINGS = (z.WARNINGS)[:zb0002]
			} else {
				z.WARNINGS = make([]string, zb0002)
			}
			for za0001 := range z.WARNINGS {
				z.WARNINGS[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "WARNINGS", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Response) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "REID"
	err = en.Append(0x85, 0xa4, 0x52, 0x45, 0x49, 0x44)
	if err != nil {
		return
	}
	err = z.REID.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "REID")
		return
	}
	// write "RNUM"
	err = en.Append(0xa4, 0x52, 0x4e, 0x55, 0x4d)
	if err != nil {
		return
	}
	err = en.WriteInt(z.RNUM)
	if err != nil {
		err = msgp.WrapError(err, "RNUM")
		return
	}
	// write "RESPONSE"
	err = en.Append(0xa8, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45)
	if err != nil {
		return
	}
	err = en.WriteString(z.RESPONSE)
	if err != nil {
		err = msgp.WrapError(err, "RESPONSE")
		return
	}
	// write "PAYL"
	err = en.Append(0xa4, 0x50, 0x41, 0x59, 0x4c)
	if err != nil {
		return
	}
	err = z.PAYL.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "PAYL")
		return
	}
	// write "WARNINGS"
	err = en.Append(0xa8, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x53)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.WARNINGS)))
	if err != nil {
		err = msgp.WrapError(err, "WARNINGS")
		return
	}
	for za0001 := range z.WARNINGS {
		err = en.WriteString(z.WARNINGS[za0001])
		if err != nil {
			err = msgp.WrapError(err, "WARNINGS", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Response) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "REID"
	o = append(o, 0x85, 0xa4, 0x52, 0x45, 0x49, 0x44)
	o, err = z.REID.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "REID")
		return
	}
	// string "RNUM"
	o = append(o, 0xa4, 0x52, 0x4e, 0x55, 0x4d)
	o = msgp.AppendInt(o, z.RNUM)
	// string "RESPONSE"
	o = append(o, 0xa8, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45)
	o = msgp.AppendString(o, z.RESPONSE)
	// string "PAYL"
	o = append(o, 0xa4, 0x50, 0x41, 0x59, 0x4c)
	o, err = z.PAYL.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "PAYL")
		return
	}
	// string "WARNINGS"
	o = append(o, 0xa8, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x53)
	o = msgp.AppendArrayHeader(o, uint32(len(z.WARNINGS)))
	for za0001 := range z.WARNINGS {
		o = msgp.AppendString(o, z.WARNINGS[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Response) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "REID":
			bts, err = z.REID.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "REID")
				return
			}
		case "RNUM":
			z.RNUM, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RNUM")
				return
			}
		case "RESPONSE":
			z.RESPONSE, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RESPONSE")
				return
			}
		case "PAYL":
			bts, err = z.PAYL.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "PAYL")
				return
			}
		case "WARNINGS":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WARNINGS")
				return
			}
			if cap(z.WARNINGS) >= int(zb0002) {
				z.WARNINGS = (z.WARNINGS)[:zb0002]
			} else {
				z.WARNINGS = make([]string, zb0002)
			}
			for za0001 := range z.WARNINGS {
				z.WARNINGS[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WARNINGS", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Response) Msgsize() (s int) {
	s = 1 + 5 + z.REID.Msgsize() + 5 + msgp.IntSize + 9 + msgp.StringPrefixSize + len(z.RESPONSE) + 5 + z.PAYL.Msgsize() + 9 + msgp.ArrayHeaderSize
	for za0001 := range z.WARNINGS {
		s += msgp.StringPrefixSize + len(z.WARNINGS[za0001])
	}
	return
}
